config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  get 'top' => 'homes#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully crested."
      redirect_to book_path(@book.id)
    
    else
    @books = Book.all
      render :index
    end
  end
  
  
  def show
    @book = Book.find(params[:id])  
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト  
  end
  
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<%= flash[:notice] %>
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %> 

  <div>
  Title<br>
  <%= f.text_field :title %><br>
  </div>
  <div>
  Body<br>
  <%= f.text_area :body %>
  </div>
  <div><%= f.submit 'Update Book' %></div>
  
  <td><%= link_to 'Show',book_path %></td>
  |
  <td><%= link_to 'Back', books_path %></td>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
     <tr>
         <th>Title</th>
         <th>Body</th>
         <th colspan="3"></th>
     </tr> 
  </thead>
  <tbody>
    <% @books.each do |book| %> 
    <tr>
    <td><%= book.title %></td> 
    <td><%= book.body %></td>
    <td><%= link_to 'Show',book_path(book.id)%></td>
    <td><%= link_to 'Edit',edit_book_path(book.id)%></td>
    <td><%= link_to 'Destroy',book_path(book.id), method: :delete, "data-confirm"=>"本当に削除しますか？"%></td>
</tr>
<% end %>
  </tbody>
</table>


<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book do |f| %> 
<div class="field">
 <label for="book_title">Title</label>
  <%= f.text_field :title %>
</div>
  
<div class="field">
  <label for="book_body">Body</label>
  <%= f.text_area :body %>
  </div>
  
  <div><%= f.submit 'Create Book' %></div>
<% end %>

app/views/books/show.html.erb
<%= flash[:notice] %>
<body>
  <p><strong>Title: </strong><%= @book.title %></p>

  <p><strong>Body: </strong><%= @book.body %></p>

  <td><%= link_to 'Edit',edit_book_path %></td>
  |
  <tb><%= link_to 'Back', books_path %></tb>

</body>

app/views/homes/top.html.erb
<body>
<h1>ようこそ <strong>Bookers</strong>へ！</h1>
<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
    
<p>
<a><%= link_to 'start', books_path %></a>
</p>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>